// Creative Orchestrator — 6-Agent Pipeline with Rejection Loops
// Agency-grade creative intelligence system
// Phase 2: Master Enforcement Block integrated into Agents 2, 4, 5, 6
import { createClient } from 'npm:@supabase/supabase-js@2';
import {
  STYLE_MODES, DEFAULT_STYLE_MODE, resolveStyleMode,
  getAntiAILockInstruction, getStylePurityInstruction, getCategoryRules,
  calculateFingerprintSimilarity, extractFingerprint, isTooSimilar,
  getMasterEnforcementBlock, detectLogoGeneration,
  getIdeaElevationInstruction, getVisualMaturityInstruction,
  getConceptDepthInstruction, getDribbbleSimilarityInstruction,
  getEffectDependencyInstruction, getLetterformMandate, getLogoStructuralRules,
  type BrandIntelligence, type CreativeBlueprint, type LayoutWireframeSpec,
  type QCScores, type DesignFingerprint, type StyleMode
} from '../_shared/creativeOrchestrator.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const MAX_REJECTION_LOOPS = 3;
const MAX_SENIOR_RETRIES = 1;

// Helper: Call Lovable AI Gateway for text completion (Agents 1-3, 5-6)
async function callTextAgent(
  systemPrompt: string,
  userPrompt: string,
  apiKey: string,
  model = 'gemini-2.5-flash'
): Promise<string> {
  const response = await fetch('https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.7,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    console.error(`Text agent error (${response.status}):`, err.substring(0, 300));
    throw new Error(`AI agent call failed: ${response.status}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content || '';
}

// Helper: Call Lovable AI Gateway for image generation (Agent 4)
async function callImageAgent(
  prompt: string,
  apiKey: string,
  referenceImageUrl?: string
): Promise<string> {
  const messageContent: any[] = [{ type: 'text', text: prompt }];
  
  if (referenceImageUrl) {
    messageContent.push({
      type: 'image_url',
      image_url: { url: referenceImageUrl }
    });
  }

  const response = await fetch('https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'google/gemini-3-pro-image-preview',
      messages: [{ role: 'user', content: messageContent }],
      modalities: ['image', 'text'],
      temperature: 0.8,
      quality: 'high',
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    console.error(`Image agent error (${response.status}):`, err.substring(0, 300));
    throw new Error(`Image generation failed: ${response.status}`);
  }

  const data = await response.json();
  const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if (!imageUrl) throw new Error('No image generated by Agent 4');
  return imageUrl;
}

// Helper: Call vision agent for QC/Senior review (Agents 5-6)
async function callVisionAgent(
  systemPrompt: string,
  textPrompt: string,
  imageUrl: string,
  apiKey: string
): Promise<string> {
  const response = await fetch('https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'gemini-2.5-flash',
      messages: [
        { role: 'system', content: systemPrompt },
        {
          role: 'user',
          content: [
            { type: 'text', text: textPrompt },
            { type: 'image_url', image_url: { url: imageUrl } }
          ]
        },
      ],
      temperature: 0.3,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    console.error(`Vision agent error (${response.status}):`, err.substring(0, 300));
    throw new Error(`Vision agent failed: ${response.status}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content || '';
}

// Parse JSON from LLM response (handles markdown code blocks)
function parseJSONFromResponse(text: string): any {
  // Try direct parse
  try { return JSON.parse(text); } catch {}
  
  // Try extracting from markdown code block
  const codeBlockMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (codeBlockMatch) {
    try { return JSON.parse(codeBlockMatch[1].trim()); } catch {}
  }
  
  // Try finding JSON object in text
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try { return JSON.parse(jsonMatch[0]); } catch {}
  }
  
  return null;
}

// SSE helper
function sseEvent(stage: string, status: string, detail?: string): string {
  return `data: ${JSON.stringify({ stage, status, detail })}\n\n`;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
  if (!GEMINI_API_KEY) {
    return new Response(JSON.stringify({ error: 'API key not configured' }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || '';
  const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY') || '';

  const authHeader = req.headers.get('Authorization');
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Authentication required' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: authHeader } }
  });

  const jwt = authHeader.replace('Bearer ', '');
  const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(jwt);
  if (claimsError || !claimsData?.claims?.sub) {
    return new Response(JSON.stringify({ error: 'Invalid token' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
  const userId = claimsData.claims.sub as string;

  try {
    const body = await req.json();
    const { prompt, designType, referenceImageUrl, brandSystem, useSSE } = body;

    if (!prompt || prompt.length === 0) {
      return new Response(JSON.stringify({ error: 'Prompt is required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // If SSE requested, stream progress
    if (useSSE) {
      const encoder = new TextEncoder();
      const stream = new ReadableStream({
        async start(controller) {
          try {
            const send = (stage: string, status: string, detail?: string) => {
              controller.enqueue(encoder.encode(sseEvent(stage, status, detail)));
            };

            const result = await Promise.race([
              runPipeline(
                prompt, designType, referenceImageUrl, brandSystem,
                userId, supabase, GEMINI_API_KEY, send
              ),
              new Promise((_, reject) => setTimeout(() => reject(new Error('Pipeline timeout — exceeded 50s limit')), 50000))
            ]);

            send('complete', 'done', JSON.stringify(result));
            controller.close();
          } catch (err) {
            const msg = err instanceof Error ? err.message : 'Unknown error';
            controller.enqueue(encoder.encode(sseEvent('error', 'failed', msg)));
            controller.close();
          }
        }
      });

      return new Response(stream, {
        headers: { ...corsHeaders, 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' }
      });
    }

    // Non-SSE: run pipeline with 50s hard timeout safety net
    const result = await Promise.race([
      runPipeline(
        prompt, designType, referenceImageUrl, brandSystem,
        userId, supabase, GEMINI_API_KEY
      ),
      new Promise((_, reject) => setTimeout(() => reject(new Error('Pipeline timeout — exceeded 50s limit')), 50000))
    ]);

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    console.error('Orchestrator error:', msg);
    return new Response(JSON.stringify({ error: msg }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});

// Main pipeline
async function runPipeline(
  prompt: string,
  designType: string | undefined,
  referenceImageUrl: string | undefined,
  brandSystem: any | undefined,
  userId: string,
  supabase: any,
  apiKey: string,
  onProgress?: (stage: string, status: string, detail?: string) => void
): Promise<{
  imageUrl: string;
  filePath: string;
  conceptName: string;
  conceptIdea: string;
  styleMode: string;
  shouldWatermark: boolean;
}> {
  const progress = onProgress || (() => {});

  // ═══════════════════════════════════════════════════
  // PIPELINE ROUTING — Detect logo generation
  // ═══════════════════════════════════════════════════
  const isLogo = detectLogoGeneration(prompt, designType);
  const effectiveDesignType = isLogo ? 'logo' : (designType || 'campaign');
  console.log(`🔍 Logo detection: ${isLogo ? 'YES — activating Layers 2,3,4,9' : 'NO — general design mode'}`);

  // ═══════════════════════════════════════════════════
  // AGENT 1 — BRAND STRATEGIST
  // ═══════════════════════════════════════════════════
  progress('brand_strategist', 'active', 'Analyzing brief...');
  console.log('🎯 Agent 1: Brand Strategist');

  const agent1System = `You are a senior brand strategist at a global branding agency. Extract brand intelligence from the user's brief.
Return a JSON object with these fields:
- category, subcategory
- audience: { age_range, sophistication_level, income_tier, geographic_market }
- positioning, tone, visual_maturity, risk_tolerance, competitive_archetype
- brand_personality_traits (array), price_positioning

If the brief is vague, default to: Modern, premium, globally competitive, minimal.
Return ONLY valid JSON, no explanation.`;

  const agent1Response = await callTextAgent(agent1System, prompt, apiKey);
  let brandIntelligence = parseJSONFromResponse(agent1Response);
  
  if (!brandIntelligence) {
    console.warn('Agent 1 failed to return JSON, using defaults');
    brandIntelligence = {
      category: effectiveDesignType,
      subcategory: 'general',
      audience: { age_range: '25-45', sophistication_level: 'high', income_tier: 'upper-middle', geographic_market: 'global' },
      positioning: 'premium', tone: 'confident', visual_maturity: 'high',
      risk_tolerance: 'moderate', competitive_archetype: 'challenger',
      brand_personality_traits: ['modern', 'refined', 'trustworthy'],
      price_positioning: 'premium'
    };
  }

  progress('brand_strategist', 'completed');
  console.log('✅ Agent 1 complete:', brandIntelligence.category);

  // ═══════════════════════════════════════════════════
  // BUILD MASTER ENFORCEMENT BLOCK (Phase 2)
  // ═══════════════════════════════════════════════════
  const brandName = prompt.split(' ').slice(0, 5).join(' '); // Extract brand name from prompt start
  const enforcementBlock = getMasterEnforcementBlock(brandName, brandIntelligence.category, effectiveDesignType);
  console.log(`🛡️ Master Enforcement Block active — ${isLogo ? 'ALL 9 layers' : 'Layers 1,5,6,7,8'}`);

  // ═══════════════════════════════════════════════════
  // AGENT 2 — CREATIVE DIRECTOR (+ Phase 2 Enforcement)
  // ═══════════════════════════════════════════════════
  progress('creative_director', 'active', 'Setting creative direction...');
  console.log('🎨 Agent 2: Creative Director');

  const resolvedStyle = resolveStyleMode(prompt);
  const antiAILock = getAntiAILockInstruction();
  const stylePurity = getStylePurityInstruction(resolvedStyle);

  const agent2System = `You are a senior creative director at a London-based branding agency. Define the creative blueprint.

Available style modes: ${STYLE_MODES.join(', ')}

${antiAILock}

${stylePurity}

${enforcementBlock}

Return a JSON object with:
- core_idea (one sentence)
- visual_metaphor (single metaphor)
- layout_philosophy
- typography_system: { primary, secondary } (max 2 typefaces, NEVER default to Inter/Montserrat)
- color_discipline: { palette (array of hex), max_colors: 3 }
- image_style (photography rules or illustration rules)
- negative_space_strategy
- exclusion_list (array of things to avoid)
- locked_style_mode (one of the available modes)

Return ONLY valid JSON.`;

  const agent2Response = await callTextAgent(
    agent2System,
    `Brand Intelligence:\n${JSON.stringify(brandIntelligence, null, 2)}\n\nOriginal Brief: ${prompt}`,
    apiKey
  );
  let creativeBlueprint = parseJSONFromResponse(agent2Response);

  if (!creativeBlueprint) {
    console.warn('Agent 2 failed to return JSON, using defaults');
    creativeBlueprint = {
      core_idea: `Premium ${brandIntelligence.category} design with editorial restraint`,
      visual_metaphor: 'precision and clarity',
      layout_philosophy: 'asymmetric balance with generous whitespace',
      typography_system: { primary: 'Space Grotesk', secondary: 'DM Sans' },
      color_discipline: { palette: ['#1a1a1a', '#f5f5f0', '#2563eb'], max_colors: 3 },
      image_style: 'editorial photography, natural lighting, no HDR',
      negative_space_strategy: 'minimum 40% breathing space',
      exclusion_list: [...(new Set([...['clipart', 'gradient blobs', 'glow effects']]))],
      locked_style_mode: resolvedStyle,
    };
  }

  // Force style mode
  creativeBlueprint.locked_style_mode = creativeBlueprint.locked_style_mode || resolvedStyle;

  progress('creative_director', 'completed');
  console.log('✅ Agent 2 complete. Style:', creativeBlueprint.locked_style_mode);

  // Rejection loop tracking
  let rejectionCount = 0;
  let seniorRetryCount = 0;
  let finalImageUrl: string | null = null;
  let finalCompositionSpec: LayoutWireframeSpec | null = null;

  while (rejectionCount <= MAX_REJECTION_LOOPS) {
    // ═══════════════════════════════════════════════════
    // AGENT 3 — COMPOSITION ARCHITECT
    // ═══════════════════════════════════════════════════
    progress('composition_architect', 'active', rejectionCount > 0 ? `Redesigning layout (attempt ${rejectionCount + 1})...` : 'Composing layout...');
    console.log(`📐 Agent 3: Composition Architect (attempt ${rejectionCount + 1})`);

    // Fetch recent fingerprints to enforce variety
    let recentFingerprints: DesignFingerprint[] = [];
    try {
      const { data: fpData } = await supabase
        .from('design_fingerprints')
        .select('grid_type, focal_position, text_placement, image_proportion, alignment_style, whitespace_ratio, style_mode')
        .eq('user_id', userId)
        .order('created_at', { ascending: false })
        .limit(5);
      
      if (fpData) recentFingerprints = fpData;
    } catch (e) {
      console.warn('Failed to fetch fingerprints:', e);
    }

    const avoidanceInstruction = recentFingerprints.length > 0
      ? `\n\nAVOID these recent layouts (force structural variety):\n${recentFingerprints.map((fp, i) => 
          `${i + 1}. Grid: ${fp.grid_type}, Focal: ${fp.focal_position}, Alignment: ${fp.alignment_style}`
        ).join('\n')}`
      : '';

    const agent3System = `You are a composition architect specializing in award-winning layouts.

HARD RULES:
- Max 2 typefaces
- Max 3 colors
- Minimum 40% negative space
- Single focal anchor per canvas
- No more than 2 content blocks for social posts
- No decorative shapes unless concept-justified
- Typography ratios: Heading:Subheading = 1.4, Subheading:Body = 1.2
- Center alignment ONLY if editorial style
${avoidanceInstruction}

Return a JSON object with:
- grid_system, margin_system, focal_hierarchy
- type_scale_ratio: { heading_to_subheading, subheading_to_body }
- image_text_ratio, alignment_rules, whitespace_minimum (decimal 0-1)
- max_typefaces (2), max_colors (3), focal_anchor, content_blocks (number)

Return ONLY valid JSON.`;

    const agent3Response = await callTextAgent(
      agent3System,
      `Creative Blueprint:\n${JSON.stringify(creativeBlueprint, null, 2)}`,
      apiKey
    );
    let compositionSpec = parseJSONFromResponse(agent3Response);

    if (!compositionSpec) {
      compositionSpec = {
        grid_system: '12-column asymmetric', margin_system: '8px base unit',
        focal_hierarchy: 'primary element dominant', 
        type_scale_ratio: { heading_to_subheading: 1.4, subheading_to_body: 1.2 },
        image_text_ratio: '60:40', alignment_rules: 'left-aligned with intentional offset',
        whitespace_minimum: 0.45, max_typefaces: 2, max_colors: 3,
        focal_anchor: 'upper-left golden ratio point', content_blocks: 2
      };
    }

    // Enforce fingerprint variety
    const newFingerprint = extractFingerprint(compositionSpec, creativeBlueprint.locked_style_mode);
    if (isTooSimilar(newFingerprint, recentFingerprints)) {
      console.warn('⚠️ Layout too similar to recent outputs, forcing variation');
      compositionSpec.grid_system = compositionSpec.grid_system === '12-column asymmetric' ? '8-column modular' : '12-column asymmetric';
      compositionSpec.focal_anchor = compositionSpec.focal_anchor === 'center' ? 'upper-right offset' : 'lower-left dynamic';
    }

    finalCompositionSpec = compositionSpec;
    progress('composition_architect', 'completed');
    console.log('✅ Agent 3 complete. Grid:', compositionSpec.grid_system);

    // ═══════════════════════════════════════════════════
    // AGENT 4 — ASSET GENERATOR (+ Phase 2 Enforcement)
    // ═══════════════════════════════════════════════════
    progress('asset_generator', 'active', 'Generating design...');
    console.log('🖼️ Agent 4: Asset Generator');

    const categoryRules = getCategoryRules(brandIntelligence.category);

    // Build logo-specific enforcement for Agent 4's prompt
    const logoEnforcementForPrompt = isLogo
      ? `\n\n${getLetterformMandate()}\n\n${getLogoStructuralRules()}`
      : '';

    // Format-aware canvas rules per design type
    const designTypeLC = (designType || '').toLowerCase();
    let canvasRule: string;
    if (isLogo) {
      canvasRule = `Generate a 1:1 SQUARE image. Center the logo with generous padding — minimum 15% clear space on ALL sides. Solid white (#FFFFFF) background. Do NOT fill edge-to-edge.
NO 3D effects. NO glow. NO shadows. NO gradients. NO metallic/chrome. Flat, clean, vector-ready ONLY.
TEXT RULE: Only render the exact brand NAME. Do NOT add any tagline, slogan, subtitle, or description text. The brief is for creative reference only — do NOT render it as text.
COLOR RULE: Logo mark uses maximum 1-2 colors. Background is solid white. Total: 2 logo colors + 1 background = 3 max.`;
    } else if (designTypeLC === 'social_media') {
      canvasRule = `Generate a 1:1 SQUARE image (1080×1080px). Minimum 10% safe zone on all edges. NO generic gradient cards. NO Canva aesthetics. Clean, flat, contemporary. TEXT RULE: Do NOT add text not specified in the brief.`;
    } else if (designTypeLC === 'poster') {
      canvasRule = `Generate a 2:3 PORTRAIT format image. Full-bleed composition. TEXT RULE: Do NOT add text not specified in the brief. NO centered text blocks with generic gradients.`;
    } else if (designTypeLC === 'campaign') {
      canvasRule = `Generate a 16:9 landscape or 4:5 portrait — pick whichever suits the concept. Single hero visual, NOT a collage. TEXT RULE: Do NOT add text not specified in the brief.`;
    } else if (designTypeLC === 'app_poster') {
      canvasRule = `Generate a 9:16 VERTICAL format image. Device frame must be current-gen (iPhone 15 Pro style). TEXT RULE: Do NOT add text not specified in the brief.`;
    } else if (designTypeLC === 'ecommerce') {
      canvasRule = `Generate a product image on pure white (#FFFFFF) background. Product must be photorealistic. TEXT RULE: Do NOT add text not specified in the brief.`;
    } else {
      canvasRule = `Generate a SINGLE image. Fill the entire canvas edge-to-edge. TEXT RULE: Do NOT add text not specified in the brief.`;
    }
    const logoCanvasRule = canvasRule;

    const imagePrompt = `Create a single, polished, agency-grade design.

CONCEPT: ${creativeBlueprint.core_idea}
VISUAL METAPHOR: ${creativeBlueprint.visual_metaphor}
STYLE MODE: ${creativeBlueprint.locked_style_mode}

LAYOUT:
- Grid: ${compositionSpec.grid_system}
- Focal anchor: ${compositionSpec.focal_anchor}
- Whitespace minimum: ${Math.round(compositionSpec.whitespace_minimum * 100)}%
- Max ${compositionSpec.max_typefaces} typefaces: ${creativeBlueprint.typography_system?.primary || 'Space Grotesk'}, ${creativeBlueprint.typography_system?.secondary || 'DM Sans'}
- Max ${compositionSpec.max_colors} colors: ${(creativeBlueprint.color_discipline?.palette || ['#1a1a1a', '#f5f5f0']).join(', ')}

TYPOGRAPHY: ${creativeBlueprint.typography_system?.primary || 'Space Grotesk'} for headlines, ${creativeBlueprint.typography_system?.secondary || 'DM Sans'} for body.

IMAGE STYLE: ${creativeBlueprint.image_style}

CATEGORY RULES: ${categoryRules}

ORIGINAL BRIEF: ${prompt}

${antiAILock}
${enforcementBlock}
${logoEnforcementForPrompt}

${logoCanvasRule} This must look like it came from a premium branding agency — not a template generator.`;

    finalImageUrl = await callImageAgent(imagePrompt, apiKey, referenceImageUrl);
    
    progress('asset_generator', 'completed');
    console.log('✅ Agent 4 complete. Image generated.');

    // ═══════════════════════════════════════════════════
    // AGENT 5 — QUALITY CONTROL REVIEWER (Phase 2 Expanded)
    // ═══════════════════════════════════════════════════
    progress('quality_control', 'active', 'Reviewing quality...');
    console.log('🔍 Agent 5: Quality Control');

    const agent5System = `You are a senior QC reviewer at a global branding agency. Score this design from 1-10 on ALL 10 dimensions:
- clarity, hierarchy, restraint, originality, professional_maturity, concept_strength
- strategic_distinctiveness, typographic_refinement, memorability, system_scalability

If ANY score is below 8, set overall_pass to false and provide rejection_reason.

Also check:
- Does it contain any AI artifacts (gradient blobs, floating circles, clipart)?
- Is there sufficient negative space (40%+)?
- Is it a single focused concept (not multi-concept)?

${getDribbbleSimilarityInstruction()}

${getEffectDependencyInstruction()}

${getConceptDepthInstruction()}

${getVisualMaturityInstruction()}

Return ONLY a JSON object with: clarity, hierarchy, restraint, originality, professional_maturity, concept_strength, strategic_distinctiveness, typographic_refinement, memorability, system_scalability, overall_pass (boolean), rejection_reason (string or null).`;

    const agent5Response = await callVisionAgent(
      agent5System,
      `Review this design against the brief: "${prompt}"\nStyle mode: ${creativeBlueprint.locked_style_mode}\nCore idea: ${creativeBlueprint.core_idea}\nDesign type: ${effectiveDesignType}`,
      finalImageUrl,
      apiKey
    );

    let qcScores = parseJSONFromResponse(agent5Response);
    
    if (!qcScores) {
      console.warn('Agent 5 failed to return JSON, passing by default');
      qcScores = {
        clarity: 8, hierarchy: 8, restraint: 8, originality: 8,
        professional_maturity: 8, concept_strength: 8,
        strategic_distinctiveness: 8, typographic_refinement: 8,
        memorability: 8, system_scalability: 8,
        overall_pass: true
      };
    }

    console.log('📊 QC Scores:', qcScores);

    if (!qcScores.overall_pass && rejectionCount < MAX_REJECTION_LOOPS) {
      console.warn(`❌ QC REJECTED (attempt ${rejectionCount + 1}): ${qcScores.rejection_reason}`);
      progress('quality_control', 'rejected', qcScores.rejection_reason || 'Quality below threshold');
      rejectionCount++;
      continue; // Loop back to Agent 3
    }

    progress('quality_control', 'completed');

    // ═══════════════════════════════════════════════════
    // AGENT 6 — SENIOR CREATIVE APPROVAL (Phase 2 Stricter)
    // ═══════════════════════════════════════════════════
    progress('senior_approval', 'active', 'Final review...');
    console.log('👔 Agent 6: Senior Approval');

    const agent6System = `You are a senior creative director giving final approval. Answer ONE question:
"Would this pass review at a global branding agency charging premium retainers?"

${getIdeaElevationInstruction()}

${getVisualMaturityInstruction()}

DELIVERY RULE: Maximum 3 concepts may be presented. Quality over quantity.
If this design does not meet the bar, reject it.

Return ONLY a JSON object: { "approved": true/false, "reason": "..." }
If not approved, explain why briefly.`;

    const agent6Response = await callVisionAgent(
      agent6System,
      `Brief: ${prompt}\nConcept: ${creativeBlueprint.core_idea}\nStyle: ${creativeBlueprint.locked_style_mode}\nDesign type: ${effectiveDesignType}`,
      finalImageUrl,
      apiKey
    );

    let seniorApproval = parseJSONFromResponse(agent6Response);
    
    if (!seniorApproval) {
      seniorApproval = { approved: true }; // Default pass
    }

    if (!seniorApproval.approved && seniorRetryCount < MAX_SENIOR_RETRIES && rejectionCount < MAX_REJECTION_LOOPS) {
      console.warn(`❌ Senior REJECTED: ${seniorApproval.reason}`);
      progress('senior_approval', 'rejected', seniorApproval.reason || 'Did not meet agency standards');
      seniorRetryCount++;
      rejectionCount++;
      continue; // Loop back to Agent 3
    }

    progress('senior_approval', 'completed');
    console.log('✅ Agent 6: APPROVED');
    break; // Exit rejection loop — design approved
  }

  if (!finalImageUrl) {
    throw new Error('Pipeline failed to produce an approved design after all attempts');
  }

  // ═══════════════════════════════════════════════════
  // UPLOAD & FINGERPRINT STORAGE
  // ═══════════════════════════════════════════════════
  progress('finalizing', 'active', 'Uploading...');

  // Upload to storage
  const base64Data = finalImageUrl.includes('base64,') ? finalImageUrl.split('base64,')[1] : finalImageUrl;
  const binaryData = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
  const fileName = `${userId}/orchestrated/${crypto.randomUUID()}.png`;

  const { error: uploadError } = await supabase.storage
    .from('design-assets')
    .upload(fileName, binaryData, { contentType: 'image/png', upsert: false });

  if (uploadError) {
    console.error('Upload failed:', uploadError);
    throw new Error('Failed to upload image');
  }

  const { data: signedUrlData } = await supabase.storage
    .from('design-assets')
    .createSignedUrl(fileName, 86400);

  if (!signedUrlData?.signedUrl) {
    throw new Error('Failed to generate signed URL');
  }

  // Store fingerprint
  if (finalCompositionSpec) {
    const fp = extractFingerprint(finalCompositionSpec, creativeBlueprint.locked_style_mode);
    try {
      await supabase.from('design_fingerprints').insert({
        user_id: userId,
        grid_type: fp.grid_type,
        focal_position: fp.focal_position,
        text_placement: fp.text_placement,
        image_proportion: fp.image_proportion,
        alignment_style: fp.alignment_style,
        whitespace_ratio: fp.whitespace_ratio,
        style_mode: fp.style_mode,
      });
      console.log('✅ Fingerprint stored');
    } catch (e) {
      console.warn('Fingerprint storage failed:', e);
    }
  }

  // Check watermark
  const { data: tierData } = await supabase
    .from('credits')
    .select('subscription_tier')
    .eq('user_id', userId)
    .single();

  progress('finalizing', 'completed');

  return {
    imageUrl: signedUrlData.signedUrl,
    filePath: fileName,
    conceptName: creativeBlueprint.core_idea?.split(' ').slice(0, 4).join(' ') || 'Creative Concept',
    conceptIdea: creativeBlueprint.core_idea || 'Premium design concept',
    styleMode: creativeBlueprint.locked_style_mode || DEFAULT_STYLE_MODE,
    shouldWatermark: tierData?.subscription_tier === 'free',
  };
}
