// @ts-nocheck
// Generate Design Edge Function v2.1 - Added retry logic and partial success handling
import { createClient } from 'npm:@supabase/supabase-js@2';
import { z } from 'npm:zod@3';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
  'Access-Control-Allow-Credentials': 'true',
};

const GenerateDesignRequestSchema = z.object({
  prompt: z.string().min(1).max(6000),
  design_type: z.string().optional().default('design'),
  model: z.string().optional().default('google/gemini-3-pro-image-preview'),
  referenceImageUrl: z.string().url().optional().nullable(),
  brandSystem: z.object({
    colors: z.object({
      primary: z.object({ hex: z.string(), name: z.string() }).optional(),
      secondary: z.object({ hex: z.string(), name: z.string() }).optional(),
      accent: z.object({ hex: z.string(), name: z.string() }).optional(),
    }).optional(),
    typography: z.object({
      primary_font: z.string().optional(),
      secondary_font: z.string().optional(),
      font_weights: z.array(z.number()).optional(),
    }).optional(),
    style: z.string().optional(),
    logo_type: z.string().optional(),
  }).nullable().optional(),
  modelParams: z.object({
    output_format: z.enum(['png', 'jpeg', 'webp']).optional().default('png'),
    background: z.enum(['transparent', 'opaque', 'auto']).optional().default('auto'),
    quality: z.enum(['high', 'medium', 'low', 'auto']).optional().default('high'),
    size: z.string().optional().default('1024x1024'),
  }).optional().default({
    output_format: 'png',
    quality: 'high',
    size: '1024x1024',
    background: 'auto'
  }),
});

async function callGoogleGemini(prompt: string, referenceImageUrl?: string, modelParams?: any): Promise<string> {
  const GOOGLE_API_KEY = Deno.env.get('GOOGLE_API_KEY');
  if (!GOOGLE_API_KEY) {
    throw new Error('GOOGLE_API_KEY not configured');
  }

  const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent?key=${GOOGLE_API_KEY}`;
  
  const parts: any[] = [{ text: prompt }];
  
  // Add reference image if provided
  if (referenceImageUrl) {
    if (referenceImageUrl.startsWith('data:image')) {
      const base64Data = referenceImageUrl.split(',')[1];
      const mimeType = referenceImageUrl.match(/data:([^;]+);/)?.[1] || 'image/png';
      parts.push({
        inlineData: {
          mimeType: mimeType,
          data: base64Data
        }
      });
    } else if (referenceImageUrl.startsWith('http')) {
      // Fetch URL-based reference image and convert to base64 for Gemini
      try {
        console.log('🔗 Fetching reference image from URL...');
        const imgResp = await fetch(referenceImageUrl);
        if (imgResp.ok) {
          const imgBuffer = await imgResp.arrayBuffer();
          const uint8 = new Uint8Array(imgBuffer);
          let binary = '';
          for (let i = 0; i < uint8.length; i++) {
            binary += String.fromCharCode(uint8[i]);
          }
          const base64 = btoa(binary);
          const mimeType = imgResp.headers.get('content-type') || 'image/png';
          parts.push({ inlineData: { mimeType, data: base64 } });
          console.log('✅ Reference image fetched and converted to base64');
        }
      } catch (e) {
        console.warn('⚠️ Failed to fetch reference image:', e);
      }
    }
  }

  const response = await fetch(apiUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts }],
      generationConfig: {
        temperature: 0.4,
        topK: 32,
        topP: 1,
        maxOutputTokens: 4096,
      }
    })
  });
  
  if (!response.ok) {
    const error = await response.text();
    console.error('Google API error:', error);
    throw new Error(`Google API error: ${response.status}`);
  }
  
  const data = await response.json();
  const imagePart = data.candidates?.[0]?.content?.parts?.find((p: any) => p.inlineData);
  
  if (!imagePart?.inlineData?.data) {
    throw new Error('No image generated by Google Gemini');
  }
  
  // CRITICAL FIX: Return base64 for upload to storage (not data URL)
  return imagePart.inlineData.data;
}

async function callOpenAIImage(prompt: string, referenceImageUrl?: string, modelParams?: any): Promise<string> {
  const OPENAI_API_KEY = Deno.env.get('OPENAI_API_KEY');
  if (!OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY not configured');
  }

  // If reference image is provided, use image editing endpoint
  if (referenceImageUrl) {
    // For editing, we'd need to use the edits endpoint with a mask
    // For now, we'll use generation with the prompt
    console.log('⚠️ OpenAI image editing with reference not yet implemented, using generation');
  }

  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${OPENAI_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'gpt-image-1',
      prompt: prompt,
      n: 1,
      size: modelParams?.size || '1024x1024',
      quality: modelParams?.quality || 'high',
      output_format: modelParams?.output_format || 'png',
      background: modelParams?.background || 'auto',
      output_compression: 100,
    }),
  });
  
  if (!response.ok) {
    const error = await response.text();
    console.error('OpenAI API error:', error);
    
    if (response.status === 402) {
      throw new Error('OpenAI account has insufficient credits');
    }
    throw new Error(`OpenAI API error: ${response.status}`);
  }
  
  const data = await response.json();
  
  if (!data.data?.[0]?.b64_json) {
    throw new Error('No image generated by OpenAI');
  }
  
  return `data:image/png;base64,${data.data[0].b64_json}`;
}

// Detect design type from prompt
// BUG FIX #7: Map "branding" to "logo" - user wants logos, not brand guidelines
const detectDesignType = (prompt: string): string => {
  const lower = prompt.toLowerCase();
  
  // Brand guidelines detection (BEFORE generic brand catch-all)
  if (lower.includes('brand guidelines') || lower.includes('brand guideline') || lower.includes('guideline cover') || lower.includes('guideline page')) return 'brand_guidelines';
  // Explicit type keywords (priority order matters)
  // Ecommerce/marketplace detection (BEFORE logo catch-all)
  if (lower.includes('ecommerce') || lower.includes('e-commerce') || lower.includes('amazon') || lower.includes('product listing') || lower.includes('marketplace') || lower.includes('shopify') || lower.includes('product image') || lower.includes('product photo')) return 'ecommerce';
  // Social media detection
  if (lower.includes('social media') || lower.includes('instagram') || lower.includes('facebook post') || lower.includes('social post') || lower.includes('linkedin post') || lower.includes('twitter post') || lower.includes('tiktok') || lower.includes('social content')) return 'social_media';
  // App poster/screenshot detection
  if (lower.includes('app store') || lower.includes('app screenshot') || lower.includes('app poster') || lower.includes('app banner') || lower.includes('play store')) return 'app_poster';
  // Existing types
  if (lower.includes('campaign') || lower.includes('advertising') || lower.includes('ad campaign') || lower.includes('marketing campaign')) return 'campaign';
  if (lower.includes('mockup') || lower.includes('product mock')) return 'mockup';
  if (lower.includes('character design') || lower.includes('mascot')) return 'character';
  if (lower.includes('illustration') || lower.includes('editorial art')) return 'illustration';
  if (lower.includes('poster')) return 'poster';
  if (lower.includes('logo') || lower.includes('branding') || lower.includes('brand identity') || lower.includes('brand')) return 'logo';
  
  // Default to illustration for ambiguous requests (not logo)
  return 'illustration';
};

// Font pairings and color directions removed — AI now selects contextually appropriate styling from the brief

// Logo style randomization for variety (kept for logo designs only)
const LOGO_STYLES = [
  { name: 'Geometric Minimalism', brief: 'Pure geometric forms. Mathematical precision. Negative space as primary design element. Think Paul Rand, Massimo Vignelli.' },
  { name: 'Typographic Wordmark', brief: 'Letter-driven identity. Custom lettering or refined type treatment. No symbol — the name IS the logo. Think Zara, Supreme, Google.' },
  { name: 'Abstract Symbol + Type', brief: 'Original abstract mark paired with clean sans-serif. Symbol should be ownable and non-literal. Think Nike swoosh, Airbnb, Spotify.' },
  { name: 'Monogram / Lettermark', brief: 'Initials or single letter as primary mark. Architectural, structured composition. Think IBM, HBO, Chanel.' },
  { name: 'Organic / Hand-crafted', brief: 'Natural forms with human touch. Imperfect but intentional line quality. Think Patagonia, Whole Foods.' },
  { name: 'Brutalist / Industrial', brief: 'Raw, utilitarian, unapologetically bold. Heavy type, stark contrast, zero decoration. Think Supreme, Vetements.' },
  { name: 'Swiss / International Style', brief: 'Grid-based, rational, clean. Helvetica-adjacent but custom. Think Swiss railway, Braun.' },
  { name: 'Dynamic / Responsive', brief: 'Logo system that suggests movement or adaptability. Could work as animated mark. Think MIT Media Lab, Melbourne.' },
];

function getRandomLogoStyle() {
  return LOGO_STYLES[Math.floor(Math.random() * LOGO_STYLES.length)];
}

// Get comprehensive design-type-specific prompt templates
const getDesignTypePrompt = (designType: string, enhancedPrompt: string, referenceImageUrl?: string): string => {

  const brandFidelityRule = `Brand name must appear EXACTLY as written in the brief. Do not rename, abbreviate, or substitute it. Do not add text (taglines, slogans, descriptions) that was not explicitly requested.`;

  const promptTemplates: Record<string, string> = {
    logo: (() => {
      const style = getRandomLogoStyle();
      console.log('🎲 Random logo style selected:', style.name);
      const logoPrefix = `Generate a 1:1 square logo image. Center the logo with generous padding — minimum 15% clear space on ALL sides. Solid white (#FFFFFF) background. Do NOT fill edge-to-edge. The logo must breathe.
NO 3D effects. NO glow. NO shadows. NO gradients. NO metallic/chrome effects. NO bevels. Flat, clean, vector-ready output ONLY.
`;
      const antiTaglineRule = `TEXT RULE: Only render the exact brand NAME as text. Do NOT add any tagline, slogan, subtitle, description, or concept text. The design brief is for YOUR creative reference only — do NOT render brief text in the image. If the user did not explicitly say "add tagline: ...", then NO tagline appears.`;
      const antiGenericRule = `ANTI-GENERIC MANDATE: No clipart. No stock vector packs. No template aesthetics. No Canva/Fiverr/99designs look. Output must be indistinguishable from a top-tier London or NYC design agency.`;
      return `${logoPrefix}${brandFidelityRule}
${antiTaglineRule}
${antiGenericRule}

STYLE DIRECTION: ${style.name}
${style.brief}

QUALITY STANDARDS:
- Strong silhouette — must work in pure black on white at 16px favicon size
- Typography should feel engineered, not default — consider optical kerning and character refinement
- If a symbol is used, avoid literal icons for the industry (no coffee cup for coffee brand, no leaf for eco brand)
- NO decorative elements, NO ornamental flourishes, NO swirls, NO rays, NO starbursts.
- NO icons that literally represent the industry (no coffee cup for coffee brand, no gear for tech, no globe for travel, no leaf for eco).
- Every element must serve a structural purpose. If it can be removed without losing meaning, remove it.

COLOR RULE (follow precisely):
- The logo MARK/SYMBOL uses maximum 1-2 colors only. Keep it restrained.
- Background: solid white (#FFFFFF). This counts as the 3rd color.
- Total palette: 2 logo colors + 1 background = 3 maximum across the entire image.
- Logo must also work in pure monochrome (single color on white).
- Readability: Brand name must be instantly readable at any size. Typography contrast is non-negotiable.
- Minimum 4.5:1 contrast ratio between all text and background.
- Pentagram / Wolff Olins / Landor portfolio level quality and intentionality
- Output must feel authored by a senior designer, not generated

DESIGN BRIEF: ${enhancedPrompt}
`;
    })(),

    branding: `Generate a 1:1 square image. Professional brand identity system on white background.
${brandFidelityRule}

Cohesive brand identity layout: primary logo top-center, 4-5 color swatches with hex codes, typography specimen showing heading and body fonts, one pattern element derived from the logo. Grid-based Swiss design composition with generous margins. Business card or stationery preview showing the system applied. Every element must feel like one unified system.

DESIGN BRIEF: ${enhancedPrompt}
`,

    poster: `Generate a 2:3 portrait image. Full-bleed poster composition.
${brandFidelityRule}

Exhibition-quality poster. Strong 3-level typographic hierarchy: display headline, medium subhead, light body. Rule-of-thirds composition with focal point at a power intersection. Maximum 4 cohesive colors. Minimum 30% negative space. Headline readable from 3 meters. Contemporary editorial design, not stock-template aesthetic.

DESIGN BRIEF: ${enhancedPrompt}
`,

    character: `Generate a 1:1 square image. Character design on clean background.
${brandFidelityRule}

Full-body character with strong distinctive silhouette recognizable as a solid black shape. Dynamic 3/4 pose showing personality. Expressive face readable at thumbnail size. Intentional costume design communicating role. Consistent stylized proportions. Limited palette of 5-7 colors. Pixar/DreamWorks concept art level appeal and polish.

DESIGN BRIEF: ${enhancedPrompt}
`,

    illustration: `Generate a 1:1 square image. Editorial illustration.
${brandFidelityRule}

Single clear visual metaphor understood in 3-5 seconds. Intentional limited palette of 4-6 harmonious colors. Strong focal point with clear visual hierarchy. Authored artistic style with textural quality. Considered edge relationships within the frame. Every element serves the concept. New Yorker / NYT editorial illustration quality.

DESIGN BRIEF: ${enhancedPrompt}
`,

    mockup: `Generate a 4:3 landscape image. Photorealistic product mockup.
${brandFidelityRule}

Product with design clearly applied in realistic context. True-to-life materials and textures. Professional studio lighting with natural shadows. Product fills 50-70% of frame. 3/4 view angle with slight background blur (f/2.8-f/5.6). Minimal contextual props. Apple product page level photography quality.

DESIGN BRIEF: ${enhancedPrompt}
`,

    campaign: `Generate a 16:9 landscape image. Advertising campaign key visual.
${brandFidelityRule}

Single strategic concept understood in under 5 seconds. One dominant hero visual, not a collage. Bold premium headline typography. Brand identity naturally integrated without dominating. Clear visual hierarchy: image → headline → subtext → CTA. Minimum 25% negative space. Consistent design language extensible to OOH, digital, print.

DESIGN BRIEF: ${enhancedPrompt}
`,

    ecommerce: `Generate a 1:1 square image. E-commerce product hero shot.
${brandFidelityRule}

Pure white (#FFFFFF) background. Product fills 85%+ of frame. Photorealistic, not illustrated. Professional studio lighting: soft key light, subtle fill, clean shadows. Most flattering angle (3/4 view for most products). True-to-life colors without over-saturation. No text overlays on the hero image.

DESIGN BRIEF: ${enhancedPrompt}
`,

    social_media: `Generate a 1:1 square image (1080×1080px).
${brandFidelityRule}

Professional social media post. Bold editorial composition with a single clear message. 10% safe zone padding on all edges. Mobile-readable typography — headline max 8 words, large and bold. Contemporary 2024-2026 design aesthetic. Clean, flat, high-contrast. Generous whitespace (40%+ breathing room). Brand identity present but not overwhelming.

DESIGN BRIEF: ${enhancedPrompt}
`,

    app_poster: `Generate a 9:16 vertical image. App store promotional screenshot.
${brandFidelityRule}

Bold benefit-driven headline, maximum 6 words in premium display typeface. Current-gen device mockup (iPhone 15 Pro or Pixel 8 style) showing realistic app UI. Clean gradient or solid color background complementing the app brand. Visual hierarchy: headline → device mockup → supporting text. Device frame must be current-gen with thin bezels.

DESIGN BRIEF: ${enhancedPrompt}
`,

    brand_guidelines: `Generate a 9:16 portrait image (768x1365px). Professional brand guideline document page.
${brandFidelityRule}

This is a single page of a professional brand guidelines document. Use the reference image as the brand's logo — replicate it EXACTLY as provided, do not generate or invent a new logo. 
Layout: Clean editorial design with generous whitespace, professional typography, structured grid layout. Magazine-quality typographic hierarchy. Premium brand manual aesthetic.
The page should look like it belongs in a professionally designed brand book from a top-tier design agency (Pentagram, Wolff Olins level).

DESIGN BRIEF: ${enhancedPrompt}
`
  };

  return promptTemplates[designType] || promptTemplates['illustration'];
};

function getSafeErrorMessage(error: Error): string {
  console.error('Detailed error:', {
    message: error.message,
    stack: error.stack,
    timestamp: new Date().toISOString(),
  });
  
  if (error.message.includes('Unauthorized') || error.message.includes('authorization')) {
    return 'Authentication required';
  }
  if (error.message.includes('not found')) {
    return 'Resource not found';
  }
  if (error.message.includes('AI Gateway error')) {
    return 'AI service temporarily unavailable';
  }
  if (error.message.includes('Invalid')) {
    return 'Invalid request format';
  }
  if (error.message.includes('not configured')) {
    return 'Service configuration error';
  }
  
  return 'An error occurred. Please try again later.';
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('No authorization header');
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    );

    const token = authHeader.replace('Bearer ', '');
    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    if (claimsError || !claimsData?.claims?.sub) {
      throw new Error('Unauthorized');
    }
    const user = { id: claimsData.claims.sub as string };

    const body = await req.json();

    // ═══════════ ORCHESTRATOR ROUTING ═══════════
    // When useOrchestrator is true (default), route through the 6-agent creative pipeline
    const useOrchestrator = body.useOrchestrator === true; // Must explicitly opt in — direct path is reliable
    
    if (useOrchestrator) {
      console.log('🎭 Routing through creative-orchestrator pipeline');
      
      const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || '';
      const orchestratorUrl = `${SUPABASE_URL}/functions/v1/creative-orchestrator`;
      
      // 20s timeout for orchestrator — fail fast so fallback has time
      const orchController = new AbortController();
      const orchTimeout = setTimeout(() => orchController.abort(), 20000);
      
      let orchResponse: Response;
      try {
        orchResponse = await fetch(orchestratorUrl, {
          method: 'POST',
          headers: {
            'Authorization': authHeader,
            'Content-Type': 'application/json',
            'apikey': Deno.env.get('SUPABASE_ANON_KEY') || '',
          },
          body: JSON.stringify({
            prompt: body.prompt,
            designType: body.design_type,
            referenceImageUrl: body.referenceImageUrl,
            brandSystem: body.brandSystem,
            useSSE: body.useSSE || false,
          }),
          signal: orchController.signal,
        });
      } catch (fetchErr: any) {
        clearTimeout(orchTimeout);
        console.warn('⚠️ Orchestrator fetch failed/timed out:', fetchErr.message);
        console.log('⚠️ Falling back to direct generation');
        orchResponse = null as any;
      }
      clearTimeout(orchTimeout);

      if (!orchResponse || !orchResponse.ok) {
        if (orchResponse) {
          const errText = await orchResponse.text();
          console.error('Orchestrator error:', orchResponse.status, errText.substring(0, 200));
        }
        console.log('⚠️ Falling back to direct generation');
      } else {
        // SSE passthrough
        if (body.useSSE) {
          return new Response(orchResponse.body, {
            headers: { ...corsHeaders, 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' }
          });
        }
        
        const orchResult = await orchResponse.json();
        console.log('✅ Orchestrator returned result');
        
        return new Response(JSON.stringify({
          imageUrl: orchResult.imageUrl,
          filePath: orchResult.filePath,
          shouldWatermark: orchResult.shouldWatermark,
          success: true,
          enhanced_prompt: body.prompt,
          conceptName: orchResult.conceptName,
          conceptIdea: orchResult.conceptIdea,
          styleMode: orchResult.styleMode,
          orchestrated: true,
        }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200,
        });
      }
    }
    // ═══════════ END ORCHESTRATOR ROUTING ═══════════
    
    let validated;
    try {
      validated = GenerateDesignRequestSchema.parse(body);
      console.log('✅ Request validation passed');
      console.log('🎨 DESIGN TYPE RECEIVED:', {
        timestamp: new Date().toISOString(),
        design_type: validated.design_type || 'not provided',
        prompt_preview: validated.prompt.slice(0, 100),
        model: validated.model
      });
    } catch (validationError) {
      if (validationError instanceof z.ZodError) {
        console.error('❌ Request validation failed:', {
          errors: validationError.errors.map(e => ({
            path: e.path.join('.'),
            message: e.message,
            code: e.code
          })),
          receivedBody: {
            hasPrompt: !!body.prompt,
            promptLength: body.prompt?.length,
            hasReferenceImage: !!body.referenceImageUrl,
            referenceImageFormat: body.referenceImageUrl?.substring(0, 50),
            model: body.model
          }
        });
        
        return new Response(
          JSON.stringify({ 
            error: 'Invalid request parameters',
            details: validationError.errors.map(e => ({
              field: e.path.join('.'),
              issue: e.message,
              received: e.path.reduce((obj: any, key) => obj?.[key], body)
            }))
          }),
          {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 400,
          }
        );
      }
      throw validationError;
    }
    
    const { prompt, referenceImageUrl, brandSystem } = validated;

    // Start with raw prompt
    let enhancedPrompt = prompt;
    
    // Reference analysis removed - image passed directly to Gemini for visual replication
    if (referenceImageUrl) {
      console.log('📸 Reference image will be passed directly to Gemini for visual replication');
    }
    
    // Category detection for premium quality standards
    const detectCategory = (prompt: string): string => {
      const lower = prompt.toLowerCase();
      if (lower.includes('ecommerce') || lower.includes('e-commerce') || lower.includes('amazon') || lower.includes('product listing') || lower.includes('marketplace') || lower.includes('shopify')) return 'ecommerce';
      if (lower.includes('social media') || lower.includes('instagram') || lower.includes('facebook post') || lower.includes('social post') || lower.includes('linkedin')) return 'social_media';
      if (lower.includes('app store') || lower.includes('app poster') || lower.includes('app screenshot') || lower.includes('play store')) return 'app_poster';
      if (lower.includes('logo') || lower.includes('branding') || lower.includes('brand identity')) return 'branding';
      if (lower.includes('poster')) return 'poster';
      if (lower.includes('illustration')) return 'illustration';
      if (lower.includes('character')) return 'character';
      if (lower.includes('campaign') || lower.includes('advertisement') || lower.includes('marketing')) return 'campaign';
      return 'general';
    };

    const category = detectCategory(prompt);
    
    // Detect branding asset requests (need clean, flat, isolated assets)
    const isBrandAssetRequest =
      // Explicit brand asset keywords (uppercase from structured prompts)
      prompt.includes('SINGLE LOGO ONLY') ||
      prompt.includes('LOGO VARIATIONS') ||
      prompt.includes('COLOR SWATCHES ONLY') ||
      prompt.includes('TYPOGRAPHY SYSTEM') ||
      prompt.includes('LOGO USAGE') ||
      prompt.includes('BRAND PHOTOGRAPHY') ||
      prompt.includes('PRIMARY LOGO') ||
      prompt.includes('COLOR PALETTE') ||
      prompt.includes('TYPOGRAPHY SPECIMEN') ||
      prompt.includes('PHOTOGRAPHY STYLE') ||
      
      // Natural language branding requests (case-insensitive)
      /\b(logo|branding|brand identity|brand asset|color palette|typography|brand guideline|brand manual)\b/i.test(prompt) ||
      
      // Common branding phrases
      prompt.toLowerCase().includes('design a logo') ||
      prompt.toLowerCase().includes('create a logo') ||
      prompt.toLowerCase().includes('professional branding') ||
      prompt.toLowerCase().includes('brand design') ||
      prompt.toLowerCase().includes('logo concept') ||
      prompt.toLowerCase().includes('brand colors') ||
      prompt.toLowerCase().includes('brand typography');
    
    console.log('🔍 Branding detection analysis:', {
      isBrandAsset: isBrandAssetRequest,
      promptSnippet: prompt.substring(0, 100),
      matchedKeywords: {
        hasExplicitKeyword: /SINGLE LOGO|PRIMARY LOGO|COLOR SWATCHES/i.test(prompt),
        hasNaturalLanguage: /\b(logo|branding|brand identity)\b/i.test(prompt),
        hasBrandingPhrase: prompt.toLowerCase().includes('professional branding')
      }
    });
    
    const isBrandGuideline = isBrandAssetRequest; // Keep backward compatibility
    
    // ONLY add brand context for explicit brand guideline requests
    if (isBrandGuideline && brandSystem && brandSystem !== null) {
      const brandDetails = [];
      if (brandSystem.colors?.primary) {
        brandDetails.push(`Primary color: ${brandSystem.colors.primary.hex}`);
      }
      if (brandSystem.typography?.primary_font) {
        brandDetails.push(`Primary font: ${brandSystem.typography.primary_font}`);
      }
      
      if (brandDetails.length > 0) {
        enhancedPrompt = `${enhancedPrompt}\n\nBrand Guidelines Context:\n${brandDetails.join(', ')}\n\nIMPORTANT: Create a clean, isolated design element on white background. Focus on the single requested element only.`;
        console.log('🎯 Brand guideline with context');
      }
    }
    
    console.log('✨ Final prompt preview (first 200 chars):', enhancedPrompt.substring(0, 200));

    // Check user credits before proceeding
    const CREDIT_COST = 10; // Cost for image generation
    const { data: creditData, error: creditError } = await supabase
      .from('credits')
      .select('balance')
      .eq('user_id', user.id)
      .single();

    if (creditError) {
      throw new Error('Failed to fetch credits');
    }

    if (!creditData || creditData.balance < CREDIT_COST) {
      return new Response(
        JSON.stringify({ 
          error: 'insufficient_credits',
          message: 'Insufficient credits. Please upgrade your plan to continue.',
          required: CREDIT_COST,
          available: creditData?.balance || 0
        }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 402,
        }
      );
    }

    // Always use Lovable AI Gateway - it's pre-configured and has best reliability
    const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
    
    if (!GEMINI_API_KEY) {
      console.error('❌ GEMINI_API_KEY not configured - this should never happen in Lovable Cloud');
      return new Response(
        JSON.stringify({ 
          error: 'CONFIGURATION_ERROR',
          message: 'Image generation service is not configured. Please contact support.',
        }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 500,
        }
      );
    }
    
    console.log('🔀 Routing to: Lovable AI Gateway');
    console.log('🎨 Requested model:', validated.model);
    console.log('📝 Generating image with prompt:', enhancedPrompt.substring(0, 200));
    console.log('🖼️  Reference image provided:', !!referenceImageUrl);
    if (referenceImageUrl) {
      console.log('🔗 Reference URL preview:', referenceImageUrl.substring(0, 50) + '...');
    }

    // Build the message content with comprehensive design-type prompts
    const messageContent: any[] = [];
    
    // Detect design type from prompt or use provided type
    const designType = validated.design_type || detectDesignType(prompt);
    
    console.log('🎨 Design type detected:', designType);
    console.log('📋 Using comprehensive prompt template for:', designType);
    
    // Get comprehensive prompt template for this design type
    let comprehensivePrompt = getDesignTypePrompt(designType, enhancedPrompt, referenceImageUrl);
    
    // BRAND COLOR ENFORCEMENT: Inject brand palette as top-level directive for ALL design types
    if (brandSystem && !isBrandGuideline) {
      const brandColors: string[] = [];
      const bs = brandSystem as any;
      if (bs.colors?.primary?.hex) brandColors.push(`Primary: ${bs.colors.primary.hex}`);
      if (bs.colors?.secondary?.hex) brandColors.push(`Secondary: ${bs.colors.secondary.hex}`);
      if (bs.colors?.accent?.hex) brandColors.push(`Accent: ${bs.colors.accent.hex}`);
      if (bs.colors?.background?.hex) brandColors.push(`Background: ${bs.colors.background.hex}`);
      
      if (brandColors.length > 0) {
        const brandDirective = `MANDATORY BRAND PALETTE — use these exact colors throughout the design:\n${brandColors.map(c => `• ${c}`).join('\n')}\nDo NOT deviate from this palette. All backgrounds, text, accents, and decorative elements must use these brand colors.\n\n`;
        comprehensivePrompt = brandDirective + comprehensivePrompt;
        console.log('🎨 Brand palette injected as top-level directive for design type:', designType);
      }
    }
    
    console.log('✨ Comprehensive prompt preview (first 300 chars):', comprehensivePrompt.substring(0, 300));
    
    // Add text prompt
    messageContent.push({
      type: 'text',
      text: comprehensivePrompt
    });
    
    // Add reference image with smart context-aware instruction — let AI decide based on user's prompt
    if (referenceImageUrl) {
      messageContent.push({
        type: 'text',
        text: `REFERENCE IMAGE ATTACHED. Read the user's prompt carefully to understand their INTENT for this reference:
- If they want something "similar" or "like this" → match the style/quality but create original work
- If they want a "sister brand" or "variant" → create something related but distinctly different
- If they want to "improve" or "redesign" → use it as a starting point and elevate
- If they show a product and the prompt is about product listing/ecommerce → that IS the product to feature (replicate it exactly)
- If no specific instruction about the reference → use it as style/quality inspiration only
The user's words ALWAYS take priority over any default behavior.`
      });
      messageContent.push({
        type: 'image_url',
        image_url: { url: referenceImageUrl }
      });
    }

    const messages: any[] = [{
      role: 'user',
      content: messageContent
    }];
    
    console.log('🚀 Sending raw prompt with zero restrictions');
    
    let imageUrl: string | null = null;
    let usedLovableAI = false;

    // Deduct credits upfront BEFORE generation
    console.log(`💰 Deducting ${CREDIT_COST} credits upfront for image generation`);
    
    const { data: deductSuccess, error: deductError } = await supabase
      .rpc('deduct_credits', { 
        _user_id: user.id, 
        _amount: CREDIT_COST 
      });

    if (deductError || !deductSuccess) {
      console.error('Error deducting credits:', deductError);
      throw new Error('Insufficient credits');
    }

    // Tag this ledger entry with detailed event info
    try {
      const { designType, format, brandId } = (typeof body === 'object' && body) ? body as any : {} as any;
      const eventType = designType === 'collateral' ? 'collateral' : 'generation';
      await supabase.rpc('tag_last_credit_transaction', {
        _user_id: user.id,
        _event_type: eventType,
        _metadata: { source: 'generate-design', credits: CREDIT_COST, designType, format, brandId }
      });
    } catch (e) { console.warn('Ledger tag failed:', e); }

    try {
      // Use Lovable AI Gateway
      console.log('📡 Calling Lovable AI Gateway for image generation');
      usedLovableAI = true;
      
      const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
      if (!GEMINI_API_KEY) {
        throw new Error('GEMINI_API_KEY not configured - please contact support');
      }
      
      // Retry logic: Try up to 2 times with 1 second delay between attempts
      let retries = 0;
      const maxRetries = 2;
      
      while (!imageUrl && retries < maxRetries) {
        try {
          if (retries > 0) {
            console.log(`⚠️ Retry attempt ${retries}/${maxRetries - 1} after 1 second delay...`);
            await new Promise(resolve => setTimeout(resolve, 1000));
          }
          
          const aiResponse = await fetch('https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${GEMINI_API_KEY}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              model: 'google/gemini-3-pro-image-preview',
              messages: messages,
              modalities: ['image', 'text'],
              temperature: 0.8,
              quality: 'high' // Force maximum quality output
            }),
          });

          if (!aiResponse.ok) {
            const errorText = await aiResponse.text();
            console.error('❌ AI Gateway error response:', {
              status: aiResponse.status,
              statusText: aiResponse.statusText,
              errorText: errorText.substring(0, 500),
              attempt: retries + 1
            });
            
            // Handle specific error codes with detailed user messages
            if (aiResponse.status === 429) {
              console.error('🚫 Rate limit exceeded - too many requests');
              return new Response(
                JSON.stringify({ 
                  error: 'RATE_LIMIT_EXCEEDED',
                  message: 'Too many requests. Please wait 60 seconds and try again.',
                  userMessage: 'Rate limit reached. Please wait a moment before generating more images.'
                }),
                {
                  headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                  status: 429,
                }
              );
            }
            
            if (aiResponse.status === 402) {
              console.error('💳 AI service limit reached — refunding credits');
              // Refund credits using service role (add_credits requires admin)
              try {
                const serviceClient = createClient(
                  Deno.env.get('SUPABASE_URL') ?? '',
                  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
                );
                await serviceClient.from('credits').update({ balance: (creditData.balance) }).eq('user_id', user.id);
                console.log('✅ Credits restored to pre-deduction balance');
              } catch (refundErr) {
                console.error('❌ Credit refund failed:', refundErr);
              }
              return new Response(
                JSON.stringify({ 
                  error: 'PAYMENT_REQUIRED',
                  message: 'AI generation service credits exhausted. Please try again later or contact support.',
                  userMessage: 'AI generation service is temporarily unavailable due to high demand. Your credits have been refunded. Please try again in a few minutes.'
                }),
                {
                  headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                  status: 402,
                }
              );
            }
            
            // For 5xx errors, retry
            if (aiResponse.status >= 500 && retries < maxRetries - 1) {
              console.log(`⚠️ Server error, will retry (attempt ${retries + 1}/${maxRetries})`);
              retries++;
              continue;
            }
            
            // For all other errors, provide detailed message
            const errorMessage = `AI service returned error ${aiResponse.status}: ${errorText.substring(0, 200)}`;
            console.error('❌ Non-retryable error:', errorMessage);
            throw new Error(errorMessage);
          }

          const aiData = await aiResponse.json();
          console.log('✅ AI response received');
          const extractedImageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

          if (!extractedImageUrl) {
            console.error('❌ No image in AI response. Full response:', JSON.stringify(aiData).substring(0, 500));
            
            // Allow retry for empty responses
            if (retries < maxRetries - 1) {
              retries++;
              continue;
            }
            
            // After all retries, return graceful fallback instead of throwing
            console.warn('⚠️ No image generated after all retries, returning null (partial success mode)');
            return new Response(
              JSON.stringify({ 
                imageUrl: null, 
                warning: 'Image generation skipped - this variation will not be displayed',
                partialSuccess: true
              }),
              {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                status: 200,
              }
            );
          }
          
          imageUrl = extractedImageUrl;
          console.log(`✅ Image URL extracted successfully (attempt ${retries + 1}), length:`, imageUrl.length);
          
          // Enhanced quality validation
          if (imageUrl.startsWith('data:image')) {
            const base64Data = imageUrl.split(',')[1];
            const imageSizeKB = (base64Data.length * 3) / 4 / 1024;
            
            console.log('🎨 Design Quality Analysis:', {
              sizeKB: imageSizeKB.toFixed(2),
              category: validated.design_type,
              hasReference: !!referenceImageUrl,
              prompt: enhancedPrompt.substring(0, 80) + '...'
            });
            
            // Quality logging (no hard rejections - let user see results)
            if (imageSizeKB < 100) {
              console.warn('⚠️ Small image detected:', imageSizeKB.toFixed(2), 'KB - may be simplified design');
            } else if (imageSizeKB < 200) {
              console.log('📊 Compact image:', imageSizeKB.toFixed(2), 'KB');
            } else if (imageSizeKB > 1500) {
              console.log('✅ HIGH QUALITY: Large detailed image (', imageSizeKB.toFixed(2), 'KB)');
            } else {
              console.log('✓ Standard quality:', imageSizeKB.toFixed(2), 'KB');
            }
          }
          
          // Quality validation passed - comprehensive prompts handle correctness
          
          break; // Success, exit retry loop
          
        } catch (error) {
          console.error(`❌ Attempt ${retries + 1} failed:`, error.message);
          retries++;
          
          if (retries >= maxRetries) {
            // Allow partial success instead of complete failure
            console.warn('⚠️ All retry attempts exhausted, allowing partial success');
            return new Response(
              JSON.stringify({ 
                imageUrl: null, 
                warning: 'Image generation failed after retries - this variation will be skipped',
                partialSuccess: true
              }),
              {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                status: 200,
              }
            );
          }
        }
      }

      if (!imageUrl) {
        throw new Error('No image generated from any provider');
      }

      console.log('✅ Image generated successfully, credits already deducted');
    } catch (error) {
      // Refund credits on any generation failure
      await supabase.rpc('add_credits', {
        _user_id: user.id,
        _amount: CREDIT_COST
      });
      console.log(`♻️ Refunded ${CREDIT_COST} credits due to generation error: ${error instanceof Error ? error.message : 'Unknown error'}`);
      throw error;
    }

    // CRITICAL FIX: Upload base64 image to storage bucket, return signed URL only
    console.log('📦 Uploading image to storage bucket...');
    
    // Convert base64 to blob
    const base64Data = imageUrl.includes('base64,') ? imageUrl.split('base64,')[1] : imageUrl;
    const binaryData = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
    
    // Upload to design-assets bucket - path must start with user.id for RLS
    const fileName = `${user.id}/generated/${crypto.randomUUID()}.png`;
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('design-assets')
      .upload(fileName, binaryData, {
        contentType: 'image/png',
        upsert: false
      });
    
    if (uploadError) {
      console.error('❌ Storage upload failed:', uploadError);
      throw new Error('Failed to upload image to storage');
    }
    
    console.log('✅ Image uploaded to storage:', fileName);
    
    // Generate signed URL (24 hour expiry)
    const { data: signedUrlData, error: signedUrlError } = await supabase.storage
      .from('design-assets')
      .createSignedUrl(fileName, 86400); // 24 hours
    
    if (signedUrlError || !signedUrlData?.signedUrl) {
      console.error('❌ Failed to generate signed URL:', signedUrlError);
      throw new Error('Failed to generate signed URL');
    }
    
    const finalImageUrl = signedUrlData.signedUrl;
    console.log('✅ Signed URL generated:', finalImageUrl.substring(0, 80) + '...');

    // Apply watermark for free tier users
    const { data: tierData } = await supabase
      .from('credits')
      .select('subscription_tier')
      .eq('user_id', user.id)
      .single();

    const shouldWatermark = tierData?.subscription_tier === 'free';
    
    console.log(`✅ Image uploaded to storage, returning signed URL`);
    console.log(`🎨 Should watermark: ${shouldWatermark} (tier: ${tierData?.subscription_tier})`);

    return new Response(
      JSON.stringify({ 
        imageUrl: finalImageUrl,
        filePath: fileName, // Include file path for future URL refresh
        shouldWatermark,
        success: true,
        enhanced_prompt: enhancedPrompt // Return for frontend to use in variations
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error) {
    const status = error instanceof z.ZodError ? 400 : 500;
    return new Response(
      JSON.stringify({ error: getSafeErrorMessage(error) }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status,
      }
    );
  }
});