import type { PresentationTheme } from '@/types/presentation';

export const defaultThemes: PresentationTheme[] = [
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    preview: 'linear-gradient(135deg, #ffffff, #f4f4f5)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#18181b',
      accentColor: '#6366f1',
      backgroundColor: '#ffffff',
      surfaceColor: '#f4f4f5',
      textColor: '#18181b',
      mutedTextColor: '#71717a',
      spacingScale: 1,
      borderRadius: 12,
      cardStyle: 'elevated',
    },
  },
  {
    id: 'dark-professional',
    name: 'Dark Pro',
    preview: 'linear-gradient(135deg, #09090b, #18181b)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#fafafa',
      accentColor: '#818cf8',
      backgroundColor: '#09090b',
      surfaceColor: '#18181b',
      textColor: '#fafafa',
      mutedTextColor: '#a1a1aa',
      spacingScale: 1,
      borderRadius: 12,
      cardStyle: 'glass',
    },
  },
  {
    id: 'gradient-aurora',
    name: 'Aurora',
    preview: 'linear-gradient(135deg, #0f172a, #6366f1, #06b6d4)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#f0f9ff',
      accentColor: '#818cf8',
      backgroundColor: '#0f172a',
      surfaceColor: '#1e293b',
      textColor: '#f1f5f9',
      mutedTextColor: '#94a3b8',
      spacingScale: 1,
      borderRadius: 16,
      gradientStart: '#6366f1',
      gradientEnd: '#06b6d4',
      cardStyle: 'glass',
    },
  },
  {
    id: 'gradient-sunset',
    name: 'Sunset',
    preview: 'linear-gradient(135deg, #1a1a2e, #e94560, #f97316)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#fef2f2',
      accentColor: '#e94560',
      backgroundColor: '#1a1a2e',
      surfaceColor: '#16213e',
      textColor: '#fef2f2',
      mutedTextColor: '#fca5a5',
      spacingScale: 1.05,
      borderRadius: 16,
      gradientStart: '#e94560',
      gradientEnd: '#f97316',
      cardStyle: 'glass',
    },
  },
  {
    id: 'warm-earth',
    name: 'Warm Earth',
    preview: 'linear-gradient(135deg, #fef3c7, #f59e0b)',
    tokens: {
      headingFont: "'Georgia', serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#78350f',
      accentColor: '#f59e0b',
      backgroundColor: '#fffbeb',
      surfaceColor: '#fef3c7',
      textColor: '#451a03',
      mutedTextColor: '#92400e',
      spacingScale: 1.1,
      borderRadius: 8,
      cardStyle: 'outlined',
    },
  },
  {
    id: 'ocean-blue',
    name: 'Ocean',
    preview: 'linear-gradient(135deg, #eff6ff, #3b82f6)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#1e3a5f',
      accentColor: '#3b82f6',
      backgroundColor: '#f0f9ff',
      surfaceColor: '#e0f2fe',
      textColor: '#0c4a6e',
      mutedTextColor: '#64748b',
      spacingScale: 1,
      borderRadius: 16,
      cardStyle: 'elevated',
    },
  },
  {
    id: 'bold-contrast',
    name: 'Bold',
    preview: 'linear-gradient(135deg, #000000, #ef4444)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#ffffff',
      accentColor: '#ef4444',
      backgroundColor: '#000000',
      surfaceColor: '#1c1c1c',
      textColor: '#ffffff',
      mutedTextColor: '#a3a3a3',
      spacingScale: 1.2,
      borderRadius: 0,
      gradientStart: '#ef4444',
      gradientEnd: '#f97316',
      cardStyle: 'flat',
    },
  },
  {
    id: 'emerald-dark',
    name: 'Emerald',
    preview: 'linear-gradient(135deg, #022c22, #059669)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#ecfdf5',
      accentColor: '#10b981',
      backgroundColor: '#022c22',
      surfaceColor: '#064e3b',
      textColor: '#ecfdf5',
      mutedTextColor: '#6ee7b7',
      spacingScale: 1,
      borderRadius: 12,
      gradientStart: '#059669',
      gradientEnd: '#06b6d4',
      cardStyle: 'glass',
    },
  },
  {
    id: 'rose-cream',
    name: 'Rose',
    preview: 'linear-gradient(135deg, #fff1f2, #fb7185)',
    tokens: {
      headingFont: "'Georgia', serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#881337',
      accentColor: '#f43f5e',
      backgroundColor: '#fff1f2',
      surfaceColor: '#ffe4e6',
      textColor: '#881337',
      mutedTextColor: '#be123c',
      spacingScale: 1.05,
      borderRadius: 20,
      cardStyle: 'elevated',
    },
  },
  {
    id: 'midnight-purple',
    name: 'Midnight',
    preview: 'linear-gradient(135deg, #0c0a1a, #7c3aed, #a855f7)',
    tokens: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      primaryColor: '#f5f3ff',
      accentColor: '#a855f7',
      backgroundColor: '#0c0a1a',
      surfaceColor: '#1e1333',
      textColor: '#f5f3ff',
      mutedTextColor: '#c4b5fd',
      spacingScale: 1,
      borderRadius: 16,
      gradientStart: '#7c3aed',
      gradientEnd: '#a855f7',
      cardStyle: 'glass',
    },
  },
];
